description: Nova Scotia adds this additional amount to the age amount.
values: 
  2022-01-01: 1_465
metadata:
  unit: currency-CAD
  label: Nova Scotia basic personal amount additional base
  reference: 
  - title: 2022 Nova Scotia Personal Tax Credits Return
    href: https://hr.acadiau.ca/files/sites/hr/Payroll/Pensions%20&%20Benefits/NS_TD1_2022.pdf#page=1
  - title: Worksheet for the 2023 Nova Scotia TD1NS-WS Personal Tax Credits Return -- Age Amount Supplement
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ns-ws/td1ns-ws-23e.pdf#page=1
  - title: Nova Scotia income tax act - subdivision c - Deduction for employment out of Canada
    href: https://nslegislature.ca/sites/default/files/legc/statutes/income%20tax.pdf#page=28
