description: Alberta provides an additional disability credit of this amount, based on age.
brackets: 
  - threshold:
      2022-01-01: 0
    amount:
      2022-01-01: 11_470
  - threshold:
      2022-01-01: 18
    amount: 
      2022-01-01: 0
metadata:
  type: single_amount
  threshold_unit: year
  amount_unit: currency-CAD
  period: year
  label: Alberta disability credit additional amount base 
  reference:
  - title: Alberta Disablitiy Credit worksheet 2022 - Page 2
    href:  https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf#page=2
  - title: Alberta Income Tax Act - Section 13
    href: https://kings-printer.alberta.ca/1266.cfm?page=a30.cfm&leg_type=Acts&isbncln=9780779842674
