description: Yukon provides this base amount for the child fitness tax credit.
values:
  2022-01-01: 500
metadata:
  unit: year
  label: Yukon child fitness disability supplement
  reference:
  - title: Children's fitness tax credit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years/general-income-tax-benefit-package/yukon/5011-pc/information-residents-yukon.html#P5_cftc
