description: Canada provides this base amount in the Disability Tax Credit.
values:
  2021-01-01: 8_662
  2022-01-01: 8_870
  2023-01-01: 9_428
  2024-01-01: 9_872
  2025-01-01: 10_138
metadata:
  unit: currency-CAD
  period: year
  name: disability_credit_base
  label: disability credit base
  reference:
    - title: CRA Federal Worksheet 5000-D1 (2021) - Disability amount ($8,662)
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5000-d1/5000-d1-21e.pdf
    - title: CRA Federal Worksheet 5000-D1 (2022) - Disability amount ($8,870)
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5000-d1/5000-d1-22e.pdf
    - title: CRA Federal Worksheet 5000-D1 (2023) - Disability amount ($9,428)
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5000-d1/5000-d1-23e.pdf
    - title: CRA Federal Worksheet 5000-D1 (2024) - Disability amount ($9,872)
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5000-d1/5000-d1-24e.pdf
    - title: CRA Federal Worksheet 5000-D1 (2025) - Disability amount ($10,138)
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5000-d1/5000-d1-25e.pdf
    - title: Government of Canada - Disability tax credit
      href: https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit/claiming-dtc.html
    - title: Income Tax Act
      href: https://laws.justice.gc.ca/eng/acts/I-3.3/page-89.html#1155124-1171692
