description: Canada Child Benefit amount by child age.
brackets:
  - amount:
      2022-07-01: 6_997
      2023-07-01: 7_437
      2024-07-01: 7_787
      2025-07-01: 7_997
    threshold:
      2022-07-01: 0
  - amount:
      2022-07-01: 5_903
      2023-07-01: 6_275
      2024-07-01: 6_570
      2025-07-01: 6_748
    threshold:
      2022-07-01: 6
  - amount:
      2022-07-01: 0
    threshold:
      2022-07-01: 18
metadata:
  type: single_amount
  threshold_unit: year
  amount_unit: currency-CAD
  period: year
  name: child_benefit_amount_base
  label: Canada Child Benefit base amount
  reference:
    - title: Government of Canada - Canada Child Benefit
      href: https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/t4114/canada-child-benefit.html
    - title: CRA CCB amounts for July 2022 - June 2023 benefit year (max under 6 = $6,997, max 6-17 = $5,903)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview/canada-child-benefit-ccb-calculation-sheet-july-2022-june-2023-payments-2021-tax-year.html
    - title: CRA CCB amounts for July 2023 - June 2024 benefit year (max under 6 = $7,437, max 6-17 = $6,275)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview/canada-child-benefit-ccb-calculation-sheet-july-2023-june-2024-payments-2022-tax-year.html
    - title: CRA CCB amounts for July 2024 - June 2025 benefit year (max under 6 = $7,787, max 6-17 = $6,570)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit/canada-child-benefit-ccb-calculation-sheet-july-2024-june-2025-payments-2023-tax-year.html
    - title: CRA CCB amounts for July 2025 - June 2026 benefit year (max under 6 = $7,997, max 6-17 = $6,748)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit/canada-child-benefit-ccb-calculation-sheet-july-2025-june-2026-payments-2024-tax-year.html
