description: Yukon provides up to this amount toward the cost of registration or membership in children's fitness programs.
values:
  2022-01-01: 1_000
metadata:
  unit: currency-CAD
  label: Yukon children's fitness tax credit maximum amount
  reference:
  - title: Children's fitness tax credit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years/general-income-tax-benefit-package/yukon/5011-pc/information-residents-yukon.html#P5_cftc
