description: The annual amount you receive if you meet the age and residuence requirements but are _below_ the age threshold for the seniors increase
values:
  2022-01-01: 8226
metadata:
  unit: currency-CAD
  name: old_age_security_pension_base_amount
  label: Old Age Security Pension Base Amount
  reference:
  - title: Government of Canada - Old Age Security Pension
    href: https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security/payments.html
