description: Alberta Child and Family Benefit working amount for the third childrens.
values:
  2022-07-01: 371 # $30.91 monthly.
  2023-01-01: 393 # $32.75 monthly
metadata:
  unit: currency-CAD
  label: Alberta Child and Family Benefit the third childrens working amount
  reference:
  - title: Government of Canada - Alberta Child and Family Benefit
    href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/provincial-territorial-programs/province-alberta.html
