description: Nunavut provides this base amount for individual who is supporting their spouse or common law partner who is living in the same household. 
values:
  2022-01-01: 16_862
metadata:
  unit: currency-CAD
  label: Nunavut married status base amount
  reference:
  - title: Nunavut Income Tax Act Subvision C Section 2.14
    href: https://www.nunavutlegislation.ca/en/consolidated-law/income-tax-act-consolidation
  - title: Form NU428, Nunavut Tax
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5014-c/5014-c-22e.pdf
