description: British Columbia provides this disability credit base amount.
values:
  2022-01-01: 8_477
  2023-01-01: 8_986  
  2024-01-01: 9_435
metadata:
  unit: currency-CAD
  period: year
  label: British Columbia disability credit base amount
  reference:
  - title: B.C. basic personal income tax credits
    href: https://www2.gov.bc.ca/gov/content/taxes/income-taxes/personal/credits/basic
  - title: British Columbia Income Tax Act (4.51)
    href: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96215_00_multi#section4.51
  - title: British Columbia disability amount worksheet 2022
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5010-d/5010-d-22e.pdf#page=1
