description: Manitoba provides this base amount under the Child Tax Benefit.
values:
  2022-01-01: 420 # 35 per month

metadata:
  unit: currency-CAD
  label: Manitoba child benefit base
  period: year
  reference:
    - title: Manitoba child tax benefit 
      href: https://www.gov.mb.ca/fs/eia/mcb.html
    - title: Manitoba child benefit regulation ยง 6(1)
      href: https://www.gov.mb.ca/fs/eia_manual/regs/4.html 
