description: Alberta provides this maximum amount under the infirm dependant credit. 
values:
  2023-01-01: 12_158
metadata:
  unit: currency-CAD
  period: year
  label: Alberta infirm dependant credit maximum amount
  reference:
  - title: Alberta personal tax credits return
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab/td1ab-23e.pdf
  - title: Alberta personal tax credits return
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab-ws/td1ab-ws-23e.pdf
    
