description: British Columbia age credit base amount.
values:
  2022-01-01: 4_946
  2023-01-01: 5_243
metadata:
  unit: currency-CAD
  label: British Columbia age credit base
  reference:
    - title: B.C. basic personal income tax credits
      href: https://www2.gov.bc.ca/gov/content/taxes/income-taxes/personal/credits/basic
    - title: Income Tax Act (4.31)
      href: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96215_00_multi#section4.31
