from policyengine_canada.model_api import *


class mortgage_income(Variable):
    value_type = float
    entity = Person
    label = "Mortgage income"
    unit = CAD
    documentation = "Revenue generated by individuals through lending money to borrowers in the form of mortgages"
    definition_period = YEAR
