description: Quebec provides this base amount for age amount credit.
values:
  2022-01-01: 3_395
metadata:
  unit: currency-CAD
  label: Quebec age amount credit
  reference:
    - title: Schedule B – Tax Relief Measures
      href: https://www.revenuquebec.ca/documents/en/formulaires/tp/2022-12/TP-1.D.B-V%282022-12%29.pdf
    - title:  Revenu Quebec – Age amount, amount for a person living alone and amount for retirement income (Line 361)
      href: https://www.revenuquebec.ca/en/citizens/income-tax-return/completing-your-income-tax-return/how-to-complete-your-income-tax-return/line-by-line-help/350-to-398-1-non-refundable-tax-credits/line-361/
