description: Maximum amount that can be received per eligible child under the canada child disability benefit.
values:
  2021-01-01: 2_985
  2022-07-01: 2_985
  2023-07-01: 3_173
  2024-07-01: 3_322
  2025-07-01: 3_411
metadata:
  unit: currency-CAD
  period: year
  name: child_disability_benefit_amount
  label: Child disability benefit amount
  reference:
    - title: Government of Canada - Child disability benefit (CDB)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/child-disability-benefit.html
    - title: CRA CDB amounts for January 2021 - June 2022 benefit year (max = $2,985 per eligible child)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit/canada-child-benefit-ccb-payment-amounts.html
    - title: CRA CDB amounts for July 2022 - June 2023 benefit year (max = $2,985 per eligible child)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview/canada-child-benefit-ccb-calculation-sheet-july-2022-june-2023-payments-2021-tax-year.html
    - title: CRA CDB amounts for July 2023 - June 2024 benefit year (max = $3,173 per eligible child)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview/canada-child-benefit-ccb-calculation-sheet-july-2023-june-2024-payments-2022-tax-year.html
    - title: CRA CDB amounts for July 2024 - June 2025 benefit year (max = $3,322 per eligible child)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit/canada-child-benefit-ccb-calculation-sheet-july-2024-june-2025-payments-2023-tax-year.html
    - title: CRA CDB amounts for July 2025 - June 2026 benefit year (max = $3,411 per eligible child)
      href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit/canada-child-benefit-ccb-calculation-sheet-july-2025-june-2026-payments-2024-tax-year.html
