description: Yukon provides this base age amount credit.
values:
  2022-01-01: 
  2023-01-01: 8_369
metadata:
  unit: currency-CAD
  period: year
  label: Yukon age amount base 
  reference:
  - title: Worksheet for the Yukon 2023 Personal Tax Credits Return
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1yt-ws/td1yt-ws-23e.pdf#page=1

# TODO: 2022 values & 2022 reference & law reference
