description: Manitoba provides this spouse and common-law partner amount, equivalent to the spouses basic personal amount.
values:
  2022-01-01: 9_134
metadata:
  unit: currency-CAD
  period: year
  label: Manitoba spouse and common-law partner credit amount
  reference:
  - title: Government of Canada - 2023 Manitoba spouse and commonlaw partner amount credit
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1mb/td1mb-23e.pdf#page=1
  - title: Government of Canada - 2022 Manitoba spouse and commonlaw partner amount credit
    href: https://www.gov.mb.ca/finance/personal/pcredits.html#nrtc
  - title: Government of Canada - Manitoba individual income tax C.C.S.M C.l.10 Division II Section4.6(5)(i)
    href: https://web2.gov.mb.ca/laws/statutes/archive/i010(2020-11-05)e.php#4.6(5)
