description: Northwest Territories provides this base amount under the child benefit for older children.
brackets:
  - threshold:
      2022-07-01: 0
    amount:
      2022-07-01: 0
  - threshold:
      2022-07-01: 1
    amount:
      2022-07-01: 651.96
  - threshold:
      2022-07-01: 2
    amount:
      2022-07-01: 522
  - threshold:
      2022-07-01: 3
    amount:
      2022-07-01: 423
  - threshold:
      2022-07-01: 4
    amount:
      2022-07-01: 359.04
  - threshold:
      2022-07-01: 5
    amount:
      2022-07-01: 292.92
metadata:
  type: single_amount
  threshold_unit: child
  amount_unit: currency-CAD
  label: Northwest Territories child benefit older bracket base
  reference:
  - title: Government of Canada - Child benefit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/t4114/canada-child-benefit.html#toc18
  - title: Northwest Territories - Income Tax Act - Part 1, Division A, 3.2, (2)
    href: https://www.justice.gov.nt.ca/en/files/legislation/income-tax/income-tax.a.pdf?t1621265645728
