description: Alberta Child and Family Benefit base amount for the fourth childrens.
values:
  2022-07-01: 665 # $55.41 monthly.
  2023-01-01: 705 # $58.75 monthly.
metadata:
  unit: currency-CAD
  label: Alberta Child and Family Benefit for the fourth childrens base amount
  reference:
  - title: Government of Canada - Alberta Child and Family Benefit
    href: https://www.canada.ca/en/revenue-agency/services/child-family-benefits/provincial-territorial-programs/province-alberta.html
