description: Nunavut pension income maximun amount.
values:
  2023-01-01: 2_000
metadata:
  unit: currency-CAD
  label: Nunavut pension income maximun amount
  reference:
  - title: 2023 Nunavut Tax Credits Return
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1nu/td1nu-23e.pdf
