description: Canada caregiver amount base amount.
values:
  2022-01-01: 25_195
metadata:
  unit: currency-CAD
  period: year
  label: Canada caregiver amount base
  reference:
    - title: T1- 2022 - Amounts for Spouse or Common-Law Partner and Dependants
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5000-s5/5000-s5-22e.pdf