description: Nova Scotia exempts the following chargeable income under the Income Assistance program.
values:
  2021-01-01: 150
metadata:
  unit: currency-CAD
  label: Nova Scotia Income Assistance training allowance exemption
  reference:
    - title: Employment Support and Income Assistance Act, Section 34, Definitions (2)
      href: https://novascotia.ca/just/regulations/regs/esiaregs.htm#TOC2_4
