description: New Brunswick provide this base amount for disability amount for self.
values:
  2022-01-01: 8_757
metadata:
  unit: year
  label: New Brunswick base amount for disability amount for self
  reference:
  - title: Worksheet NB428
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5004-d/5004-d-22e.pdf